version: '3.8'
services:
  model-hub:
    build: .
    environment:
      - SERVER_PORT=8080
      - CONFIG_PATH=/etc/config.yaml
    volumes:
      - ./config.yaml:/etc/config.yaml
      - ./handler.py:/etc/handler.py
      - ./model:/models
    ports:
      - '9080:8080'